#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 2680;//value for if the colorsensor is on the line or not
	int modeSelector = 0;//0 for line follow one foe teliop
	while(modeSelector == 0){
			 if(SensorValue(lineFollowerRIGHT) > threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 63;
      motor[rightMotor] = 0;
    }
    // CENTER sensor sees dark:
    if(SensorValue(lineFollowerCENTER) > threshold)
    {
      // go straight
      motor[leftMotor]  = 63;
      motor[rightMotor] = 63;
    }
    // LEFT sensor sees dark:
    if(SensorValue(lineFollowerLEFT) > threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }

		else{
			motor[leftMotor]= 10 ;
				motor[rightMotor] = 10;
		}

	while(modeSelector == 1){
		if(vexRT[Btn6D] == 1){
			modeSelector = 1;
			}
		else{
			modeSelector = 0;
		}
			// set left side motors
		motor[leftMotor] = (vexRT[Ch3] + vexRT[Ch4]);

			// set right side motors
		motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4]);

		}
}
}
