
#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in6,    stopRobot,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  resume,         sensorTouch)
#pragma config(Sensor, dgtl4,  led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void control();
void followLine(int threshold, bool backup);
bool isButtonPressed(int press);
bool backup = false;
bool toggleController = false;
task main()
{


	int threshold = 2680;//value for if the colorsensor is on the line or not
	int modeSelector = 0;
	bool buttonPressed = false;
	while(true){
	 buttonPressed = isButtonPressed(SensorValue[touch]);



		if(buttonPressed && modeSelector == 0){
			modeSelector = 1;
			buttonPressed = false;
		}
		else if(buttonPressed && modeSelector == 1){
			modeSelector=0;
			buttonPressed = false;
		}

		if(modeSelector == 1){
			startMotor(light, 127);
			followLine(threshold, backup);
		}
		else{
			stopMotor(light);
			control();
		}
	}
}

void followLine(int threshold, bool backup){
	if(SensorValue[resume] == 0 && SensorValue(stopRobot) > 2900)
	{
		if(backup == false){
				motor[leftMotor]  = 0;
		motor[rightMotor] = 0;
		untilBump(resume);
		backup = true;
		}
	}
	else{
		backup = false;
		turnLEDOff(led);
		// Counter-steer left
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			// go straight
			motor[leftMotor]  = 32;
			motor[rightMotor] = 32;
		}
		else if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			// counter-steer right:
			motor[leftMotor]  = 127;
			motor[rightMotor] = -127;
		}
		// LEFT sensor sees dark:
		else if(SensorValue(lineFollowerLEFT) > threshold)
		{
			// counter-steer left:
			motor[leftMotor]  = -127;
			motor[rightMotor] = 127;
		}

		else{
			motor[leftMotor]= 30 ;
			motor[rightMotor] = -30;
		}
	}
}
void control(){
	if(toggleController){
		motor[leftMotor] = (vexRT[Ch3] + vexRT[Ch1]);
	  //set right side motors
		motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch1]);
	}
	else{
		stopMotor(leftMotor);
		stopMotor(rightMotor);
	}
}
bool isButtonPressed(int press){
#define BUTTON_DEBOUNCE_CHECKS 100
static unsigned int buttonState = 0;
    static char buttonPressEnabled = 1;

    if(press){
        if(buttonState < BUTTON_DEBOUNCE_CHECKS)
        {
            buttonState++;
        }
        else if(buttonPressEnabled)
        {
            buttonPressEnabled = 0;
            return true;
        }
      }
    else if(buttonState > 0 )
    {
        buttonState--;
        // alternatively you can set buttonState to 0 here, but I prefer this way
    }
    else
    {
        buttonPressEnabled = 1;
    }

    return false;
}


//if ((0 & 1 << (button - 1)) != 0) {
  //        0 &= ~(1 << (button - 1));
    //      return true;
      //  }
        //else {
        //return false;
