#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int rvalue = 2048;
	int lvalue= 2048;
	while(true){
		if(rsensor>rvalue && lsensor>lvalue){
		motor[leftMotor]=50;
		motor[rightMotor]=50;
		}
		else if(rsensor > rvalue && lsensor < lvalue){
		motor[leftMotor]=50;
		motor[rightMotor]=40;
		}
		else if(rsensor < rvalue && lsensor > lvalue){
		motor[leftMotor]=40;
		motor[rightMotor]=50;
		}
		else if(rsensor < rvalue && lsensor < lvalue){
		motor[leftMotor]=-50;
		motor[rightMotor]=-50;
		}
	}
}
